### ISSUE TITLE
No webcam crash

### ISSUE THREAD

**Issue by josmangarsal** [P2PSP/Virtual-Room#11]
When a user has not a webcam (checking `window.localStream`) use a default image avoiding the crash in the system.

**Comment by jainamritanshu** [comment]
Hi @josmanual @cristobalmedinalopez  I have created a [pull request](https://github.com/P2PSP/Virtual-Room/pull/12) to possibly resolve this issue. Kindly have a look :smile:

**Comment by josmangarsal** [comment]
Hi @jainamritanshu 

It looks you are almost there. With two peers a get one with the webcam, one black square and one avatar.

![captura de pantalla de 2017-07-20 08-46-28](https://user-images.githubusercontent.com/11162684/28404116-41f6f18e-6d28-11e7-9f60-211fe2a00858.png)

How is this possible?

**Comment by cristobalmedinalopez** [comment]
Fixed in PR #12
