### ISSUE TITLE
Pause message over the screen

### ISSUE THREAD

**Issue by josmangarsal** [P2PSP/Virtual-Room#14]
Show a message on the screen with a text like

> Paused by PeerX

while the stream is paused.

**Comment by jainamritanshu** [comment]
I guess I already put that feature of notifying every peer on a play/pause event, do you mean there should be a permanent message showing on the peer screen unless the video is player again?

**Comment by josmangarsal** [comment]
Yes @jainamritanshu, to know exactly who stopped the video. Maybe you can draw a rectangle over the screen with the text, no just a toast which is for debugging I think.

**Comment by cristobalmedinalopez** [comment]
I guess that what @josmanual says is to keep the message about who stopped the video until someone plays it again. 
I think that this issue is related to #8

**Comment by cristobalmedinalopez** [comment]
I think that it was done.
