### ISSUE TITLE
Remove "new" from room URL

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/Virtual-Room#22]
I think that the word "new" does nothing in the URL. It only makes the URL longer.

So, I propose to use:
http://127.0.0.1:3000/room/1b928792

Instead of:
http://127.0.0.1:3000/room/new/1b928792

What do you think guys?

**Comment by jainamritanshu** [comment]
Sure @cristobalmedinalopez 
I will do the needful, new seems to b e redundant here :smile:

**Comment by cristobalmedinalopez** [comment]
Done! Thanks.
