### ISSUE TITLE
Weird behaviour of File button [gui]

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/Virtual-Room#30]
Sometimes it works properly and sometimes it doesn't.

**Comment by utkarsh858** [comment]
I would like to work on it.

**Comment by cristobalmedinalopez** [comment]
Ok, great! Do you think that we could avoid to use an external library in this simple design?

**Comment by utkarsh858** [comment]
#38 Corrects it

**Comment by cristobalmedinalopez** [comment]
Thanks!
