### ISSUE TITLE
Replace '127.0.0.1' to allow any URL 

### ISSUE THREAD

**Issue by josmangarsal** [P2PSP/Virtual-Room#6]
In `room.js` replace each instance where URL is hard-coded.

For example, `http://127.0.0.1:3000` is not good and must be the URL of the webpage.

**Comment by jainamritanshu** [comment]
Hi @josmanual I have created a [pull request](https://github.com/P2PSP/Virtual-Room/pull/10) for this issued

**Comment by josmangarsal** [comment]
Hi @jainamritanshu, domainURL is not an option because the URL is still hard-coded.

You should allow to run the service in any url and port. For example, virtualroom.p2psp.org.

**Comment by cristobalmedinalopez** [comment]
Hi
I agree with @josmanual Maybe you could use `location.origin` or something like that to get the base URL.

**Comment by jainamritanshu** [comment]
Sure @cristobalmedinalopez @josmanual working on it :smile:

**Comment by jainamritanshu** [comment]
Thanks for the suggestions @cristobalmedinalopez @josmanual. I have omitted the use of any hardcoded URLs, kindly have a look :smile:

**Comment by josmangarsal** [comment]
Use `hostURL` in `signalServer` too.

**Comment by josmangarsal** [comment]
Fixed in #10, thanks!
