### ISSUE TITLE
The synchronized pause/play works properly from invited peers but not from sender

### ISSUE THREAD

**Issue by cristobalmedinalopez** [P2PSP/Virtual-Room#7]
When you press the pause/play button from the invited peers (peers joined to an existing room) it works properly taking effect in the whole team. However, when you press pause/play button from the sender peer (the room creator) it doesn't take effect in the rest of the team.

**Comment by jainamritanshu** [comment]
Hi @cristobalmedinalopez I have created a [pull request](https://github.com/P2PSP/Virtual-Room/pull/9) in reference to this issue

**Comment by cristobalmedinalopez** [comment]
Fixed in #9 
Thanks!
